version: "3.7"

services:
  web:
    build: .
    container_name: web-playlistmaker
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/web-playlistmaker

volumes:
  pgdata:
